/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jradiobutton;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author dti
 */
public class RadioButton extends javax.swing.JFrame {
    Integer tamanfonte, estilo = null;
    /**
     * Creates new form RadioButton
     */
    public RadioButton() {
        initComponents();
        buttonGroup1.add(tam1);
        buttonGroup1.add(tam2);
        buttonGroup1.add(tam3);
        buttonGroup1.add(tam4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        negrito = new javax.swing.JCheckBox();
        italico = new javax.swing.JCheckBox();
        normal = new javax.swing.JCheckBox();
        negritoitalico = new javax.swing.JCheckBox();
        rotulo1 = new javax.swing.JLabel();
        rotulo2 = new javax.swing.JLabel();
        rotulo3 = new javax.swing.JLabel();
        lista = new javax.swing.JComboBox<>();
        tam1 = new javax.swing.JRadioButton();
        tam2 = new javax.swing.JRadioButton();
        tam3 = new javax.swing.JRadioButton();
        tam4 = new javax.swing.JRadioButton();
        texto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        negrito.setText("negrito");
        negrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negritoActionPerformed(evt);
            }
        });

        italico.setText("italico");
        italico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italicoActionPerformed(evt);
            }
        });

        normal.setText("normal");
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });

        negritoitalico.setText("negritoitalico");
        negritoitalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negritoitalicoActionPerformed(evt);
            }
        });

        rotulo1.setText("Cor");

        rotulo2.setText("Estilo");

        rotulo3.setText("Tamanho");

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem Cor", "Vermelho", "Azul", "Verde", "Amarelo", "Branco", "Preto", " " }));
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        tam1.setText("12");
        tam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam1ActionPerformed(evt);
            }
        });

        tam2.setText("14");
        tam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam2ActionPerformed(evt);
            }
        });

        tam3.setText("16");
        tam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam3ActionPerformed(evt);
            }
        });

        tam4.setText("18");
        tam4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam4ActionPerformed(evt);
            }
        });

        texto.setText("Progama feito em Java");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotulo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(negritoitalico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(normal))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rotulo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(italico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(negrito))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotulo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tam1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tam2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tam3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tam4)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo1)
                    .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo2)
                    .addComponent(negritoitalico)
                    .addComponent(normal)
                    .addComponent(italico)
                    .addComponent(negrito))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo3)
                    .addComponent(tam1)
                    .addComponent(tam2)
                    .addComponent(tam3)
                    .addComponent(tam4))
                .addGap(18, 18, 18)
                .addComponent(texto)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void negritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negritoActionPerformed
        // TODO add your handling code here:
        estilo=Font.BOLD;
        normal.setSelected(false);
        italico.setSelected(false);
        negritoitalico.setSelected(false);
        texto.setFont(new Font("",estilo,tamanfonte));
    }//GEN-LAST:event_negritoActionPerformed

    private void italicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italicoActionPerformed
        // TODO add your handling code here:
        estilo=Font.ITALIC;
        normal.setSelected(false);
        negrito.setSelected(false);
        negritoitalico.setSelected(false);
        texto.setFont(new Font("",estilo,tamanfonte));
    }//GEN-LAST:event_italicoActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        // TODO add your handling code here:
        estilo=Font.PLAIN;
        negrito.setSelected(false);
        italico.setSelected(false);
        negritoitalico.setSelected(false);
        texto.setFont(new Font("",estilo,tamanfonte));
    }//GEN-LAST:event_normalActionPerformed

    private void negritoitalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negritoitalicoActionPerformed
        // TODO add your handling code here:
        estilo=Font.BOLD+Font.ITALIC;
        normal.setSelected(false);
        italico.setSelected(false);
        negrito.setSelected(false);
        texto.setFont(new Font("",estilo,tamanfonte));
    }//GEN-LAST:event_negritoitalicoActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
    if(lista.getSelectedItem().toString() == "Sem Cor" )
    texto.setForeground(Color.black);
    if(lista.getSelectedItem().toString() == "Vermelho" )
    texto.setForeground(Color.red);
    if(lista.getSelectedItem().toString() == "Azul" )
    texto.setForeground(Color.blue);
    if(lista.getSelectedItem().toString() == "Verde" )
    texto.setForeground(Color.green);
    if(lista.getSelectedItem().toString() == "Amarelo" )
    texto.setForeground(Color.yellow);
    if(lista.getSelectedItem().toString() == "Branco" )
    texto.setForeground(Color.white);
    if(lista.getSelectedItem().toString() == "Preto" )
    texto.setForeground(Color.black);
    
        
    }//GEN-LAST:event_listaActionPerformed

    private void tam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam1ActionPerformed
        // TODO add your handling code here:
        tamanfonte = 12;
        texto.setFont(new Font("",estilo,tamanfonte));
        
    }//GEN-LAST:event_tam1ActionPerformed

    private void tam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam2ActionPerformed
        // TODO add your handling code here:
        tamanfonte = 14;
        texto.setFont(new Font("",estilo,tamanfonte));
    }//GEN-LAST:event_tam2ActionPerformed

    private void tam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam3ActionPerformed
        // TODO add your handling code here:
        tamanfonte = 16;
        texto.setFont(new Font("",estilo,tamanfonte));
    }//GEN-LAST:event_tam3ActionPerformed

    private void tam4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam4ActionPerformed
        // TODO add your handling code here:
        tamanfonte = 18;
        texto.setFont(new Font("",estilo,tamanfonte));
    }//GEN-LAST:event_tam4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox italico;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JCheckBox negrito;
    private javax.swing.JCheckBox negritoitalico;
    private javax.swing.JCheckBox normal;
    private javax.swing.JLabel rotulo1;
    private javax.swing.JLabel rotulo2;
    private javax.swing.JLabel rotulo3;
    private javax.swing.JRadioButton tam1;
    private javax.swing.JRadioButton tam2;
    private javax.swing.JRadioButton tam3;
    private javax.swing.JRadioButton tam4;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
