/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastro_cliente;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author dti
 */
public class Cadastro_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Cliente
     */
    public Cadastro_Cliente() {
        initComponents();
        buttonGroup1.add(RbM);
        buttonGroup1.add(RbF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        LblPesquisar = new javax.swing.JLabel();
        LblId = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        LblEndereco = new javax.swing.JLabel();
        LblMunicipio = new javax.swing.JLabel();
        LblCep = new javax.swing.JLabel();
        LblTel = new javax.swing.JLabel();
        LblCell = new javax.swing.JLabel();
        LblCpf = new javax.swing.JLabel();
        LblCnpj = new javax.swing.JLabel();
        LblGenero = new javax.swing.JLabel();
        lista = new javax.swing.JComboBox<>();
        JtxID = new javax.swing.JTextField();
        Jtxendereco = new javax.swing.JTextField();
        JtxNome = new javax.swing.JTextField();
        JtxMunicipio = new javax.swing.JTextField();
        JtxCep = new javax.swing.JFormattedTextField();
        JtxTel = new javax.swing.JFormattedTextField();
        JtxCel = new javax.swing.JFormattedTextField();
        JtxCpf = new javax.swing.JFormattedTextField();
        JtxCnpj = new javax.swing.JFormattedTextField();
        RbM = new javax.swing.JRadioButton();
        RbF = new javax.swing.JRadioButton();
        PBtn = new javax.swing.JButton();
        BtnEnvio = new javax.swing.JButton();
        PBtn2 = new javax.swing.JButton();
        PBtn3 = new javax.swing.JButton();
        PBtn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPesquisar.setText("Pesquisar:");

        LblId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblId.setText("ID:");

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNome.setText("Nome/Empresa:");

        LblEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblEndereco.setText("Endereço:");

        LblMunicipio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblMunicipio.setText("Municipio:");

        LblCep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblCep.setText("Cep:");

        LblTel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTel.setText("Tel:");

        LblCell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblCell.setText("Cel:");

        LblCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblCpf.setText("Cpf:");

        LblCnpj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblCnpj.setText("Cnpj:");

        LblGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblGenero.setText("Genero:");

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ricardo", "Gabriela", "Pablo", "Victor", " " }));
        lista.setToolTipText("");
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        JtxID.setEditable(false);
        JtxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxIDActionPerformed(evt);
            }
        });

        Jtxendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxenderecoActionPerformed(evt);
            }
        });

        JtxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxNomeActionPerformed(evt);
            }
        });

        JtxMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxMunicipioActionPerformed(evt);
            }
        });

        try {
            JtxCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JtxCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxCepActionPerformed(evt);
            }
        });

        try {
            JtxTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JtxTel.setText("(__)___-____    ");
        JtxTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxTelActionPerformed(evt);
            }
        });

        try {
            JtxCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            JtxCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            JtxCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        RbM.setText("M");
        RbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbMActionPerformed(evt);
            }
        });

        RbF.setText("F");
        RbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbFActionPerformed(evt);
            }
        });

        PBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\dti\\Documents\\NetBeansProjects\\Cadastro_Cliente\\Zoom.gif")); // NOI18N
        PBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBtnActionPerformed(evt);
            }
        });

        BtnEnvio.setIcon(new javax.swing.ImageIcon("C:\\Users\\dti\\Documents\\NetBeansProjects\\Cadastro_Cliente\\Apply.png")); // NOI18N
        BtnEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnvioActionPerformed(evt);
            }
        });

        PBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBtn2ActionPerformed(evt);
            }
        });

        PBtn3.setIcon(new javax.swing.ImageIcon("C:\\Users\\dti\\Documents\\NetBeansProjects\\Cadastro_Cliente\\img\\format1_16x16.gif")); // NOI18N
        PBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBtn3ActionPerformed(evt);
            }
        });

        PBtn4.setIcon(new javax.swing.ImageIcon("C:\\Users\\dti\\Documents\\NetBeansProjects\\Cadastro_Cliente\\error_16x16.gif")); // NOI18N
        PBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblId)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPesquisar)
                    .addComponent(LblEndereco)
                    .addComponent(LblMunicipio)
                    .addComponent(LblCep)
                    .addComponent(LblTel)
                    .addComponent(LblCell)
                    .addComponent(LblCpf)
                    .addComponent(LblCnpj)
                    .addComponent(LblGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(JtxID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RbM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RbF))
                    .addComponent(Jtxendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JtxCnpj, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JtxCpf, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JtxCel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JtxTel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JtxCep, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JtxMunicipio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(BtnEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPesquisar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(PBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblId)
                    .addComponent(JtxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(JtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblEndereco)
                    .addComponent(Jtxendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblMunicipio)
                            .addComponent(JtxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCep)
                            .addComponent(JtxCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblTel)
                            .addComponent(JtxTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCell)
                            .addComponent(JtxCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCpf)
                            .addComponent(JtxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCnpj)
                            .addComponent(JtxCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblGenero)
                            .addComponent(RbM)
                            .addComponent(RbF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(BtnEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PBtn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxIDActionPerformed

    private void JtxenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxenderecoActionPerformed

    private void JtxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxNomeActionPerformed

    private void JtxMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxMunicipioActionPerformed

    private void JtxCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxCepActionPerformed

    private void JtxTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxTelActionPerformed

    private void RbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbMActionPerformed

    private void RbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbFActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaActionPerformed

    private void PBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBtn2ActionPerformed

    private void BtnEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnvioActionPerformed
        // TODO add your handling code here:
        String nome = JtxNome.getText();
        String endereco = (Jtxendereco.getText());
        String municipio = (JtxMunicipio.getText());
        String cep = (JtxCep.getText());
        String tel = (JtxTel.getText());
        String cel = (JtxCel.getText());
        String cpf = (JtxCpf.getText());
        String cnpj = (JtxCnpj.getText());
        String genero = "";
        if(RbM.isSelected() == true){
        genero = "M";
        } 
        if(RbF.isSelected() == true){
        genero = "F";
        } 
        JOptionPane.showMessageDialog(null, "Dados cadastrados"+"\n"+"Nome: "+nome+"\n"+"Endereço: "+endereco+"\n"+"Municipio: "+municipio+"\n"+"Cep: "+cep+"\n"+"Tel: "+tel+"\n"+"Cel: "+cel+"\n"+"Cpf: "+cpf+"\n"+"Cnpj: "+cnpj+"\n"+"Genero: "+genero+"\n");
    }//GEN-LAST:event_BtnEnvioActionPerformed

    private void PBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBtn4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_PBtn4ActionPerformed

    private void PBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBtnActionPerformed
        // TODO add your handling code here:
        if(lista.getSelectedItem().toString() == "Ricardo" ){
        JtxNome.setText("Ricardo");
        Jtxendereco.setText("joa dias 290");
        JtxMunicipio.setText("birigui");
        JtxCep.setText("324342343");
        JtxTel.setText("11543545435");
        JtxCel.setText("12545345345");
        JtxCpf.setText("32141434432");
        JtxCnpj.setText("2121322132424");
        RbM.setSelected(true);
        }
        
        if(lista.getSelectedItem().toString() == "Gabriela" ){
        JtxNome.setText("Gabriela");
        Jtxendereco.setText("prinheiro 490");
        JtxMunicipio.setText("belgo");
        JtxCep.setText("4654636565");
        JtxTel.setText("3246574757");
        JtxCel.setText("687799788786");
        JtxCpf.setText("79898798797567");
        JtxCnpj.setText("234325546576676758");
        RbF.setSelected(true);
        }
        if(lista.getSelectedItem().toString() == "Pablo" ){
        JtxNome.setText("Pablo");
        Jtxendereco.setText("razinho 890");
        JtxMunicipio.setText("barito");
        JtxCep.setText("654675767657");
        JtxTel.setText("768787699975465465");
        JtxCel.setText("4557685868568");
        JtxCpf.setText("3243465463");
        JtxCnpj.setText("32564663665464");
        RbM.setSelected(true);
        }
    
        if(lista.getSelectedItem().toString() == "Victor" ){
        JtxNome.setText("Victor");
        Jtxendereco.setText("Almas 120");
        JtxMunicipio.setText("alisoc");
        JtxCep.setText("5465464566");
        JtxTel.setText("76574676765");
        JtxCel.setText("76764765764887");
        JtxCpf.setText("7876868768");
        JtxCnpj.setText("897898798799");
        RbM.setSelected(true);
        }
       
    }//GEN-LAST:event_PBtnActionPerformed

    private void PBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBtn3ActionPerformed
        // TODO add your handling code here:
        JtxNome.setText(null);
        Jtxendereco.setText(null);
        JtxMunicipio.setText(null);
        JtxCep.setText(null);
        JtxTel.setText(null);
        JtxCel.setText(null);
        JtxCpf.setText(null);
        JtxCnpj.setText(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_PBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnvio;
    private javax.swing.JFormattedTextField JtxCel;
    private javax.swing.JFormattedTextField JtxCep;
    private javax.swing.JFormattedTextField JtxCnpj;
    private javax.swing.JFormattedTextField JtxCpf;
    private javax.swing.JTextField JtxID;
    private javax.swing.JTextField JtxMunicipio;
    private javax.swing.JTextField JtxNome;
    private javax.swing.JFormattedTextField JtxTel;
    private javax.swing.JTextField Jtxendereco;
    private javax.swing.JLabel LblCell;
    private javax.swing.JLabel LblCep;
    private javax.swing.JLabel LblCnpj;
    private javax.swing.JLabel LblCpf;
    private javax.swing.JLabel LblEndereco;
    private javax.swing.JLabel LblGenero;
    private javax.swing.JLabel LblId;
    private javax.swing.JLabel LblMunicipio;
    private javax.swing.JLabel LblPesquisar;
    private javax.swing.JLabel LblTel;
    private javax.swing.JButton PBtn;
    private javax.swing.JButton PBtn2;
    private javax.swing.JButton PBtn3;
    private javax.swing.JButton PBtn4;
    private javax.swing.JRadioButton RbF;
    private javax.swing.JRadioButton RbM;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JComboBox<String> lista;
    // End of variables declaration//GEN-END:variables
}
