/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jradiobtn;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author dti
 */
public class JradioBtn extends javax.swing.JFrame {

    /**
     * Creates new form JradioBtn
     */
    public JradioBtn() {
        
        initComponents();
        buttonGroup3.add(Primeira);
        buttonGroup3.add(Segunda);
        buttonGroup3.add(Terceira);
        buttonGroup3.add(Quarto);
        buttonGroup3.add(Quinta);
 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Primeira = new javax.swing.JRadioButton();
        Segunda = new javax.swing.JRadioButton();
        Terceira = new javax.swing.JRadioButton();
        Quinta = new javax.swing.JRadioButton();
        Quarto = new javax.swing.JRadioButton();
        exibr = new javax.swing.JButton();
        rotuloExibi = new javax.swing.JLabel();
        exibi = new javax.swing.JLabel();
        exibir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escolha uma cidade");

        Primeira.setText("Rio de Janeiro");
        Primeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeiraActionPerformed(evt);
            }
        });

        Segunda.setText("São Paulo");
        Segunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundaActionPerformed(evt);
            }
        });

        Terceira.setText("Minas Gerais");
        Terceira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerceiraActionPerformed(evt);
            }
        });

        Quinta.setText("Rio Grande do Sul");
        Quinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuintaActionPerformed(evt);
            }
        });

        Quarto.setText("Amazonas");
        Quarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuartoActionPerformed(evt);
            }
        });

        exibr.setText("Exibir");
        exibr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(rotuloExibi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Primeira)
                            .addComponent(jLabel1)
                            .addComponent(Segunda)
                            .addComponent(Terceira)
                            .addComponent(Quarto)
                            .addComponent(Quinta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(exibi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exibir)
                            .addComponent(exibr, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Primeira)
                .addGap(18, 18, 18)
                .addComponent(Segunda)
                .addGap(18, 18, 18)
                .addComponent(Terceira)
                .addGap(18, 18, 18)
                .addComponent(Quarto)
                .addGap(18, 18, 18)
                .addComponent(Quinta)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(exibr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exibir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(exibi)
                .addGap(16, 16, 16)
                .addComponent(rotuloExibi)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exibrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibrActionPerformed
        // TODO add your handling code here:
        if(Primeira.isSelected() == true)
        exibir.setText("A cidade escolhida foi: "+Primeira.getText());
        if(Segunda.isSelected() == true)
        exibir.setText("A cidade escolhida foi: "+Segunda.getText());
        if(Terceira.isSelected() == true)
        exibir.setText("A cidade escolhida foi: "+Terceira.getText());
        if(Quarto.isSelected() == true)
        exibir.setText("A cidade escolhida foi: "+Quarto.getText());
        if(Quinta.isSelected() == true)
        exibir.setText("A cidade escolhida foi: "+Quinta.getText());
    }//GEN-LAST:event_exibrActionPerformed

    private void QuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuartoActionPerformed

    private void QuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuintaActionPerformed

    private void TerceiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerceiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TerceiraActionPerformed

    private void SegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundaActionPerformed

    private void PrimeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JradioBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JradioBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JradioBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JradioBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JradioBtn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Primeira;
    private javax.swing.JRadioButton Quarto;
    private javax.swing.JRadioButton Quinta;
    private javax.swing.JRadioButton Segunda;
    private javax.swing.JRadioButton Terceira;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel exibi;
    private javax.swing.JLabel exibir;
    private javax.swing.JButton exibr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rotuloExibi;
    // End of variables declaration//GEN-END:variables
}
