/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cleantext;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author dti
 */
public class CleanText extends javax.swing.JFrame {

    /**
     * Creates new form CleanText
     */
    public CleanText() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblRNome = new javax.swing.JLabel();
        LblREnd = new javax.swing.JLabel();
        JtfTextoEnd = new javax.swing.JFormattedTextField();
        JtfTextoCida = new javax.swing.JFormattedTextField();
        LblREnd1 = new javax.swing.JLabel();
        LblREnd2 = new javax.swing.JLabel();
        LblREnd3 = new javax.swing.JLabel();
        JtfTextoNome = new javax.swing.JFormattedTextField();
        JtfTextoCep = new javax.swing.JFormattedTextField();
        JcbEstado = new javax.swing.JComboBox<>();
        BtnExibir = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblRNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblRNome.setText("Nome:");

        LblREnd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblREnd.setText("Endereço:");

        JtfTextoEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfTextoEndActionPerformed(evt);
            }
        });

        LblREnd1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblREnd1.setText("Estado:");

        LblREnd2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblREnd2.setText("Cidade:");

        LblREnd3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblREnd3.setText("Cep:");

        JtfTextoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfTextoNomeActionPerformed(evt);
            }
        });

        JtfTextoCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfTextoCepActionPerformed(evt);
            }
        });

        JcbEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "RJ", "SC", "ES", "PI", "AC", " " }));

        BtnExibir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnExibir.setText("Exibir");
        BtnExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExibirActionPerformed(evt);
            }
        });

        BtnLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        LblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblTitulo.setText("Cadastro Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LblREnd1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LblREnd2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JtfTextoCida))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LblRNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JtfTextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LblREnd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JtfTextoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(LblREnd3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnExibir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnLimpar))
                            .addComponent(JtfTextoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblTitulo)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRNome)
                    .addComponent(JtfTextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblREnd)
                    .addComponent(JtfTextoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblREnd2)
                    .addComponent(JtfTextoCida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblREnd1)
                    .addComponent(JcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblREnd3)
                    .addComponent(JtfTextoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnExibir)
                    .addComponent(BtnLimpar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfTextoEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfTextoEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfTextoEndActionPerformed

    private void JtfTextoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfTextoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfTextoNomeActionPerformed

    private void JtfTextoCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfTextoCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfTextoCepActionPerformed

    private void BtnExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExibirActionPerformed
        // TODO add your handling code here:
        
        String nome,endereco,cidade,estado,cep;
        
        nome = JtfTextoNome.getText();
        endereco = JtfTextoEnd.getText();
        cidade = JtfTextoCida.getText();
        estado = JcbEstado.getSelectedItem().toString();
        cep = JtfTextoCep.getText();
        JOptionPane.showMessageDialog(null, "Nome: "+nome+"\nEndereço: "+endereco+"\nCidade: "+cidade+"\nEstado: "+estado+"\nCep: "+cep);
    }//GEN-LAST:event_BtnExibirActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        // TODO add your handling code here:
        JtfTextoNome.setText(null);
        JtfTextoEnd.setText(null);
        JtfTextoCida.setText(null);
        JtfTextoCep.setText(null);
        JtfTextoNome.requestFocus();
  
    }//GEN-LAST:event_BtnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CleanText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CleanText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CleanText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CleanText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CleanText().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExibir;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JComboBox<String> JcbEstado;
    private javax.swing.JFormattedTextField JtfTextoCep;
    private javax.swing.JFormattedTextField JtfTextoCida;
    private javax.swing.JFormattedTextField JtfTextoEnd;
    private javax.swing.JFormattedTextField JtfTextoNome;
    private javax.swing.JLabel LblREnd;
    private javax.swing.JLabel LblREnd1;
    private javax.swing.JLabel LblREnd2;
    private javax.swing.JLabel LblREnd3;
    private javax.swing.JLabel LblRNome;
    private javax.swing.JLabel LblTitulo;
    // End of variables declaration//GEN-END:variables
}
